### ISSUE TITLE
Colab Demo

### ISSUE THREAD

**Issue by JPPPPPF** [qianlim/SCALE#16]
Hello, I tried running the colab demo, but it's not working, there seems to be issues in the cell related to downloading and setting up the libraries, anyone knows how we can solve it please? Thanks!

**Comment by amrzv** [comment]
`torch==1.6.0` is no longer available in colab.
Also, in the cell `!python main.py --config configs/config_demo.yaml` the error is raised
```python
2024-07-08 21:09:06.585961: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-08 21:09:06.586031: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-08 21:09:06.587933: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-07-08 21:09:06.613331: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-08 21:09:08.086859: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/SCALE/main.py", line 218, in <module>
    main()
  File "/content/SCALE/main.py", line 32, in main
    args = parse_config()
  File "/content/SCALE/lib/config_parser.py", line 2, in parse_config
    import configargparse
ModuleNotFoundError: No module named 'configargparse'
```

![image](https://github.com/qianlim/SCALE/assets/36787333/9262c79d-6547-4082-a10a-237c15b3e086)
